In [2]:
# create a sample dataframe
import pandas as pd
 
songs_dict = {
                'Customer': ['Aria', 'Aria', 'Aria', 'Chord', 'Chord', 'Harmony', 'Harmony', 'Harmony', 'Melody', 'Reed'],
                'Genre': ['Pop', 'Indie', 'Rock', 'Pop', 'Indie', 'Pop', 'Indie', 'Rock', 'Rock', 'Rock'],
                '# Songs': [50, 48, 1, 15, 36, 10, 5, 3, 2, 5]
             }
 
df = pd.DataFrame(songs_dict)
df

  Customer  Genre  # Songs
0     Aria    Pop       50
1     Aria  Indie       48
2     Aria   Rock        1
3    Chord    Pop       15
4    Chord  Indie       36
5  Harmony    Pop       10
6  Harmony  Indie        5
7  Harmony   Rock        3
8   Melody   Rock        2
9     Reed   Rock        5

In [3]:
pwd

'c:\\Users\\donat\\iCloudDrive\\Documents\\BIT Data Analytics\\practice\\VSCode\\Capstone_projektas'

In [6]:
customers = pd.read_csv("customers.csv")

In [7]:
customers.tail()

      Name   Age  Followers     Income Sign Up Date Discount Education Level
3   Melody  47.0        NaN  $450,000        5/5/23       No         College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes     High School
5   Selena   NaN        1.0   $62,000       8/26/23       No         College
6  Stefani   NaN        NaN   $81,000       9/24/23       No         College
7   Taylor  33.0       52.0   $60,000        9/8/23       No     High School