# Data Analyst Applicant Test Assignment

## General Requirements

**Number of tasks:** 2

**Time to complete tasks:** 7 days

**Format of submission:**

- a) A script with comments explaining the solution process.
- b) A concise report containing conclusions, recommendations, and any other information you deem necessary. The intended audience for the report is a COMPANY (e.g. LiveOps) manager.
- c) If you believe you lacked any data for a more thorough and in-depth analysis of the events, specify which data and why.

---

## Task 1

File: [`task_1.xlsx`](./data/task_1.xlsx)

**Test description:** we decided to test the sales of a gold package at a discounted rate (500 gold with a 50% discount). The offer was available to all users with a limit of 1 time per account.

**Test objective:** to increase revenue by increasing the number of paying users.

**Test period:** from 18-07-2025 to 21-07-2025

**Task:** evaluate the test results and calculate the added revenue from the test event.

### 1.1 Data understanding and preparation

**Required:**

- load the dataset;
- briefly describe the data and variables;
- check the data structure (size, columns, data types);
- assess whether there are missing values or obvious data issues.

**Result:** a short textual description and basic data overview.

### Solution:

In [1]:
import numpy as np
import pandas as pd

In [3]:
pwd

'c:\\Users\\donat\\iCloudDrive\\Documents\\BIT Data Analytics\\VII Regressions\\2026-02-24_4t_lesson'

In [8]:
df = pd.read_excel("c:\\Users\\donat\\iCloudDrive\\Documents\\BIT Data Analytics\\VII Regressions\\2026-02-24_4t_lesson\\data\\task_1.xlsx")
df.head()

          dt        revenue events
0 2025-05-01  100150.000000    NaN
1 2025-05-02  114746.937500    NaN
2 2025-05-03  109744.300078    NaN
3 2025-05-04  107270.725059    NaN
4 2025-05-05  101863.109867    NaN

General information about the data:

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   dt       103 non-null    datetime64[us]
 1   revenue  103 non-null    float64
 2   events   18 non-null     str
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 2.5 KB

Basic data statistics:

In [10]:
df.describe()

                        dt        revenue
count                  103     103.000000
mean   2025-06-21 00:00:00  102970.597434
min    2025-05-01 00:00:00   87843.063595
25%    2025-05-26 12:00:00   98276.683572
50%    2025-06-21 00:00:00  100769.437601
75%    2025-07-16 12:00:00  107261.359802
max    2025-08-11 00:00:00  127694.813839
std                    NaN    7033.341988

Number of rows and columns in the dataset:

In [11]:
df.shape

(103, 3)

Column names:

In [12]:
df.columns

Index(['dt', 'revenue', 'events'], dtype='str')

Data types in each column:

In [13]:
df.dtypes

dt         datetime64[us]
revenue           float64
events                str
dtype: object

Checking for missing values:

In [14]:
df.isna().sum()

dt          0
revenue     0
events     85
dtype: int64

Date and revenue columns do not have missing data, whereas most of the events are 
missing, indicating that no special event is recorded for those dates. We are interested
in the date range 18-07-2025 to 21-07-2025, for which we have a "test event" in events 
column.

---

### 1.2 Evaluate test results

**Required:**

- analyze the sales data during the test period;
- compare with baseline or expected behavior;
- calculate the added revenue from the test event.

**Result:** evaluation of the test with calculated added revenue.

### Solution:

In [10]:
# TODO
# ...
# ...

---

### 1.3 Conclusions and recommendations

**Required:**

- summarize the main findings from the test;
- provide recommendations for the COMPANY (e.g. LiveOps) manager;
- specify any data that was lacking for a more thorough analysis.

### Solution:

In [11]:
# TODO
# ...
# ...

---

## Task 2

File: [`task_2.xlsx`](./data/task_2.xlsx)

**Test description:** we set up an AB test with a 15% coupon for any package (1 coupon per account).

**Test objective:** to increase revenue by increasing the number of paying users.

**Test period:** from 25-10-2022 to 29-10-2022.

**Task:** evaluate the test results, calculate added revenue and added payers from the test event. The dataset should be joined using SQL.

### 2.1 Data understanding and preparation

**Required:**

- load the dataset;
- briefly describe the data and variables;
- check the data structure (size, columns, data types);
- join the dataset using SQL as specified;
- assess whether there are missing values or obvious data issues.

**Result:** a short textual description and basic data overview.

### Solution:

In [12]:
df = pd.read_excel("./data/task_2.xlsx")
df.head()

      spa_id     group_name last_payment_before_test
0  598366637   target_group            <=30 days ago
1  594900225  control_group            >=30 days ago
2  594851951   target_group            >=30 days ago
3  502502481   target_group            <=30 days ago
4  503019271   target_group            <=30 days ago

General information about the data:

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20789 entries, 0 to 20788
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   spa_id                    20789 non-null  int64
 1   group_name                20789 non-null  str
 2   last_payment_before_test  20789 non-null  str
dtypes: int64(1), str(2)
memory usage: 487.4 KB

Basic data statistics:

In [14]:
df.describe()

             spa_id
count  2.078900e+04
mean   5.558072e+08
std    3.913725e+07
min    4.999920e+08
25%    5.134990e+08
50%    5.600352e+08
75%    5.952790e+08
max    5.993355e+08

Number of rows and columns in the dataset:

In [15]:
df.shape

(20789, 3)

Column names:

In [16]:
df.columns

Index(['spa_id', 'group_name', 'last_payment_before_test'], dtype='str')

Data types in each column:

In [17]:
df.dtypes

spa_id                      int64
group_name                    str
last_payment_before_test      str
dtype: object

Checking for missing values:

In [18]:
df.isna().sum()

spa_id                      0
group_name                  0
last_payment_before_test    0
dtype: int64

Joining the dataset using SQL:

In [19]:
# TODO
# ...
# ...

Other observations:

In [20]:
# TODO
# ...
# ...

---

### 2.2 Evaluate test results

**Required:**

- analyze the AB test results;
- compare control and test groups;
- calculate the added revenue from the test event;
- calculate the added payers from the test event.

**Result:** evaluation of the AB test with calculated added revenue and added payers.

### Solution:

In [21]:
# TODO
# ...
# ...

---

### 2.3 Conclusions and recommendations

**Required:**

- summarize the main findings from the AB test;
- provide recommendations for the COMPANY (e.g. LiveOps) manager;
- specify any data that was lacking for a more thorough analysis.

### Solution:

In [22]:
# TODO
# ...
# ...